<script setup lang="ts">
import { z } from 'zod'
import type { FormSubmitEvent } from '#ui/types'
import type { User } from '~/types/auth'

// 1. Import Kubb-generated schemas
// To avoid using Kubb-generated z.union wrappers (with extra json+ld rules), we directly import the underlying Write DTO schema.
import { userUserInputUserWriteSchema } from '~/schemas/zod/user/userInputUser/writeSchema'

definePageMeta({
  layout: 'admin',
  middleware: ['auth'],
  requiredRole: 'ROLE_ADMIN'
})

const toast = useToast()

// Interface matching API Platform Hydra collection response

interface HydraResponse {
  member?: User[]
  'hydra:member'?: User[]
  totalItems?: number
  'hydra:totalItems'?: number
}

// Reactive state
const page = ref(1)
const search = ref('')
const isModalOpen = ref(false)
const selectedUser = ref<User | null>(null)
const isSubmitting = ref(false)

// Role options
const availableRoles = [
  { label: 'Client / Merchant', value: 'ROLE_CLIENT' },
  { label: 'Administrator', value: 'ROLE_ADMIN' }
]

// 2. Dynamic Zod Schema binding
// Switches between POST (Creation) and PATCH (Update) validation schemas generated by Kubb
const activeSchema = computed(() => {
  if (selectedUser.value) {
    // Extend the direct write schema for PATCH operations
    return userUserInputUserWriteSchema.extend({
      password: z
          .string()
          .min(8, {error: 'Password must be at least 8 characters'})
          .optional()
          .or(z.literal(''))
    })
  }

  // Use the clean write schema directly for POST operations
  return userUserInputUserWriteSchema
})

type UserFormState = z.output<typeof activeSchema.value>

const formState = reactive({
  email: '',
  password: '',
  roles: ['ROLE_CLIENT'] as string[]
})

// Forward browser cookies during SSR
const headers = useRequestHeaders(['cookie']) as Record<string, string>

// Fetch Users with API Platform Hydra format
const { data, pending, refresh } = await useFetch<HydraResponse>('/api/v1/users', {
  key: 'admin-users-list',
  headers,
  query: computed(() => ({
    page: page.value,
    email: search.value || undefined
  })),
  watch: [page, search],
  credentials: 'include'
})

// 3. Fallback accessor for member and totalItems keys
const users = computed(() => data.value?.member || data.value?.['hydra:member'] || [])
const totalUsers = computed(() => data.value?.totalItems || data.value?.['hydra:totalItems'] || 0)

// Table Column Definitions
const columns = [
  { accessorKey: 'id', header: 'ID' },
  { accessorKey: 'email', header: 'Email' },
  { accessorKey: 'roles', header: 'Roles' },
  { accessorKey: 'actions', header: 'Actions' }
]

// Modal Handlers
function openCreateModal() {
  selectedUser.value = null
  formState.email = ''
  formState.password = ''
  formState.roles = ['ROLE_CLIENT']
  isModalOpen.value = true
}

function openEditModal(user: User) {
  selectedUser.value = user
  formState.email = user.email
  formState.password = ''
  formState.roles = [...user.roles]
  isModalOpen.value = true
}

// 3. Submit Handler utilizing Kubb-validated data
async function handleSubmit(event: FormSubmitEvent<UserFormState>) {
  isSubmitting.value = true
  const isEditing = !!selectedUser.value

  // Strip empty password on PATCH so Symfony doesn't overwrite it with an empty string
  const payload: Record<string, any> = { ...event.data }
  if (isEditing && !payload.password) {
    delete payload.password
  }

  try {
    if (isEditing) {
      await $fetch(`/api/v1/users/${selectedUser.value!.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/merge-patch+json' },
        body: payload,
        credentials: 'include'
      })
      toast.add({ title: 'User Updated', color: 'success' })
    } else {
      await $fetch('/api/v1/users', {
        method: 'POST',
        body: payload,
        credentials: 'include'
      })
      toast.add({ title: 'User Created', color: 'success' })
    }

    isModalOpen.value = false
    await refresh()
  } catch (err: any) {
    toast.add({
      title: 'Action Failed',
      description: err.data?.detail || err.data?.['hydra:description'] || 'Unable to save user details.',
      color: 'error'
    })
  } finally {
    isSubmitting.value = false
  }
}

async function deleteUser(id: number) {
  if (!confirm('Are you sure you want to delete this user?')) return

  try {
    await $fetch(`/api/v1/users/${id}`, {
      method: 'DELETE',
      credentials: 'include'
    })
    toast.add({ title: 'User Deleted', color: 'success' })
    await refresh()
  } catch (err: any) {
    toast.add({ title: 'Delete Failed', description: err.data?.detail, color: 'error' })
  }
}
</script>

<template>
  <div class="space-y-6">
    <!-- Action Header -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
      <div>
        <h1 class="text-2xl font-bold tracking-tight">User Management</h1>
        <p class="text-sm text-gray-500 dark:text-gray-400">
          Manage system users and access roles.
        </p>
      </div>

      <UButton
          color="primary"
          icon="i-heroicons-user-plus"
          label="Add User"
          @click="openCreateModal"
      />
    </div>

    <!-- Search & Filter Controls -->
    <UCard>
      <div class="flex items-center gap-4">
        <UInput
            v-model="search"
            icon="i-heroicons-magnifying-glass"
            placeholder="Filter by email..."
            class="w-full max-w-sm"
        />
      </div>
    </UCard>

    <!-- Users Table -->
    <UCard :ui="{ body: 'p-0 sm:p-0' }">
      <UTable
          :data="users"
          :columns="columns"
          :loading="pending"
      >
        <!-- Roles Custom Cell -->
        <template #roles-cell="{ row }">
          <div class="flex flex-wrap gap-1">
            <UBadge
                v-for="role in row.original.roles"
                :key="role"
                :color="role === 'ROLE_ADMIN' ? 'warning' : 'neutral'"
                variant="subtle"
                size="xs"
            >
              {{ role }}
            </UBadge>
          </div>
        </template>

        <!-- Actions Custom Cell -->
        <template #actions-cell="{ row }">
          <div class="flex items-center justify-end gap-2">
            <UButton
                color="neutral"
                variant="ghost"
                icon="i-heroicons-pencil-square"
                size="xs"
                @click="openEditModal(row.original)"
            />
            <UButton
                color="error"
                variant="ghost"
                icon="i-heroicons-trash"
                size="xs"
                @click="deleteUser(row.original.id)"
            />
          </div>
        </template>
      </UTable>

      <!-- Table Footer / Pagination -->
      <template #footer>
        <div class="flex items-center justify-between px-4 py-2">
          <span class="text-xs text-gray-500">Total: {{ totalUsers }} users</span>
          <UPagination
              v-model:page="page"
              :total="totalUsers"
              :items-per-page="30"
          />
        </div>
      </template>
    </UCard>

    <!-- Create / Edit Slideover Modal -->
    <USlideover v-model:open="isModalOpen" :title="selectedUser ? 'Edit User' : 'Create User'">
      <template #body>
        <UForm
            :schema="activeSchema"
            :state="formState"
            class="space-y-4"
            @submit="handleSubmit"
        >
          <UFormField label="Email" name="email">
            <UInput
                v-model="formState.email"
                type="email"
                placeholder="user@example.com"
                class="w-full"
            />
          </UFormField>

          <UFormField
              label="Password"
              name="password"
              :help="selectedUser ? 'Leave empty to keep current password' : 'Minimum 8 characters'"
          >
            <UInput
                v-model="formState.password"
                type="password"
                placeholder="••••••••"
                class="w-full"
            />
          </UFormField>

          <UFormField label="Roles" name="roles">
            <USelect
                v-model="formState.roles"
                :items="availableRoles"
                multiple
                class="w-full"
            />
          </UFormField>

          <div class="flex justify-end gap-3 pt-6">
            <UButton
                color="neutral"
                variant="outline"
                label="Cancel"
                @click="isModalOpen = false"
            />
            <UButton
                type="submit"
                color="primary"
                :loading="isSubmitting"
                :label="selectedUser ? 'Save Changes' : 'Create User'"
            />
          </div>
        </UForm>
      </template>
    </USlideover>
  </div>
</template>