/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const shippingRateShippingRateOutputSchema = z.object({
  rate: z.number().optional(),
  'calculation-id': z.string().optional(),
})
