/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { hydraItemBaseSchemaSchema } from '../../hydraItemBaseSchemaSchema'

export const userJsonldUserReadSchema = hydraItemBaseSchemaSchema.extend({
  id: z.int().optional(),
  email: z.string().optional(),
  roles: z.array(z.string()).optional(),
})
