/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { carrierJsonldOrderReadSchema } from '../../carrier/jsonldOrder/readSchema'
import { hydraItemBaseSchemaSchema } from '../../hydraItemBaseSchemaSchema'

export const orderJsonldOrderReadSchema = hydraItemBaseSchemaSchema.extend({
  id: z.int().optional(),
  client: z.string().optional().meta({ examples: ['https://example.com/'] }),
  carrier: carrierJsonldOrderReadSchema.optional(),
  items: z.array(z.string()).optional(),
  shippingAddress: z.array(z.string()).optional(),
  status: z.string().optional().default('draft'),
  totalAmount: z.number().optional().default(0),
  createdAt: z.iso.datetime().optional(),
})
