/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const carrierOrderReadSchema = z.object({
  id: z.int().optional(),
  name: z.string().optional(),
  code: z.string().optional(),
})
