/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { carrierJsonldCarrierReadSchema } from './carrier/jsonldCarrier/readSchema'
import { carrierCarrierReadSchema } from './carrierCarrier/readSchema'
import { carrierCarrierWriteSchema } from './carrierCarrier/writeSchema'
import { constraintViolationJsonldSchema } from './constraintViolation/jsonldSchema'
import { constraintViolationSchema } from './constraintViolationSchema'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'

export const apiCarriersPostStatus201SchemaLdJson = carrierJsonldCarrierReadSchema

export const apiCarriersPostStatus201SchemaJson = carrierCarrierReadSchema

export const apiCarriersPostStatus201Schema = z.union([apiCarriersPostStatus201SchemaLdJson, apiCarriersPostStatus201SchemaJson])

export const apiCarriersPostStatus400SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiCarriersPostStatus400SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiCarriersPostStatus400SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiCarriersPostStatus400Schema = z.union([apiCarriersPostStatus400SchemaLdJson, apiCarriersPostStatus400SchemaProblemJson, apiCarriersPostStatus400SchemaJson])

export const apiCarriersPostStatus403SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiCarriersPostStatus403SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiCarriersPostStatus403SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiCarriersPostStatus403Schema = z.union([apiCarriersPostStatus403SchemaLdJson, apiCarriersPostStatus403SchemaProblemJson, apiCarriersPostStatus403SchemaJson])

export const apiCarriersPostStatus422SchemaLdJson = constraintViolationJsonldSchema.describe('Unprocessable entity')

export const apiCarriersPostStatus422SchemaProblemJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiCarriersPostStatus422SchemaJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiCarriersPostStatus422Schema = z.union([apiCarriersPostStatus422SchemaLdJson, apiCarriersPostStatus422SchemaProblemJson, apiCarriersPostStatus422SchemaJson])

export const apiCarriersPostResponseSchema = apiCarriersPostStatus201Schema

export const apiCarriersPostErrorSchema = z.union([apiCarriersPostStatus400Schema, apiCarriersPostStatus403Schema, apiCarriersPostStatus422Schema])

export const apiCarriersPostBodySchemaLdJson = carrierCarrierWriteSchema.describe('The new Carrier resource')

export const apiCarriersPostBodySchemaJson = carrierCarrierWriteSchema.describe('The new Carrier resource')

export const apiCarriersPostBodySchema = z.union([apiCarriersPostBodySchemaLdJson, apiCarriersPostBodySchemaJson])
