/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { carrierJsonldCarrierReadSchema } from './carrier/jsonldCarrier/readSchema'
import { carrierCarrierReadSchema } from './carrierCarrier/readSchema'
import { hydraCollectionBaseSchemaSchema } from './hydraCollectionBaseSchemaSchema'

export const apiCarriersGetCollectionQueryPageSchema = z.int().optional().default(1).describe('The collection page number')

export const apiCarriersGetCollectionStatus200SchemaLdJson = hydraCollectionBaseSchemaSchema.extend({
  member: z.array(carrierJsonldCarrierReadSchema),
}).describe('Carrier.jsonld-carrier.read collection.')

export const apiCarriersGetCollectionStatus200SchemaJson = z.array(carrierCarrierReadSchema)

export const apiCarriersGetCollectionStatus200Schema = z.union([apiCarriersGetCollectionStatus200SchemaLdJson, apiCarriersGetCollectionStatus200SchemaJson])

export const apiCarriersGetCollectionResponseSchema = apiCarriersGetCollectionStatus200Schema
