/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { carrierJsonldCarrierReadSchema } from './carrier/jsonldCarrier/readSchema'
import { carrierCarrierReadSchema } from './carrierCarrier/readSchema'
import { carrierCarrierWriteJsonMergePatchSchema } from './carrierCarrier/write/jsonMergePatchSchema'
import { constraintViolationJsonldSchema } from './constraintViolation/jsonldSchema'
import { constraintViolationSchema } from './constraintViolationSchema'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'

export const apiCarriersIdPatchPathIdSchema = z.string().describe('Carrier identifier')

export const apiCarriersIdPatchStatus200SchemaLdJson = carrierJsonldCarrierReadSchema

export const apiCarriersIdPatchStatus200SchemaJson = carrierCarrierReadSchema

export const apiCarriersIdPatchStatus200Schema = z.union([apiCarriersIdPatchStatus200SchemaLdJson, apiCarriersIdPatchStatus200SchemaJson])

export const apiCarriersIdPatchStatus400SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiCarriersIdPatchStatus400SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiCarriersIdPatchStatus400SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiCarriersIdPatchStatus400Schema = z.union([apiCarriersIdPatchStatus400SchemaLdJson, apiCarriersIdPatchStatus400SchemaProblemJson, apiCarriersIdPatchStatus400SchemaJson])

export const apiCarriersIdPatchStatus403SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiCarriersIdPatchStatus403SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiCarriersIdPatchStatus403SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiCarriersIdPatchStatus403Schema = z.union([apiCarriersIdPatchStatus403SchemaLdJson, apiCarriersIdPatchStatus403SchemaProblemJson, apiCarriersIdPatchStatus403SchemaJson])

export const apiCarriersIdPatchStatus404SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiCarriersIdPatchStatus404SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiCarriersIdPatchStatus404SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiCarriersIdPatchStatus404Schema = z.union([apiCarriersIdPatchStatus404SchemaLdJson, apiCarriersIdPatchStatus404SchemaProblemJson, apiCarriersIdPatchStatus404SchemaJson])

export const apiCarriersIdPatchStatus422SchemaLdJson = constraintViolationJsonldSchema.describe('Unprocessable entity')

export const apiCarriersIdPatchStatus422SchemaProblemJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiCarriersIdPatchStatus422SchemaJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiCarriersIdPatchStatus422Schema = z.union([apiCarriersIdPatchStatus422SchemaLdJson, apiCarriersIdPatchStatus422SchemaProblemJson, apiCarriersIdPatchStatus422SchemaJson])

export const apiCarriersIdPatchResponseSchema = apiCarriersIdPatchStatus200Schema

export const apiCarriersIdPatchErrorSchema = z.union([apiCarriersIdPatchStatus400Schema, apiCarriersIdPatchStatus403Schema, apiCarriersIdPatchStatus404Schema, apiCarriersIdPatchStatus422Schema])

export const apiCarriersIdPatchBodySchema = carrierCarrierWriteJsonMergePatchSchema.describe('The updated Carrier resource')
