/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { carrierJsonldCarrierReadSchema } from './carrier/jsonldCarrier/readSchema'
import { carrierCarrierReadSchema } from './carrierCarrier/readSchema'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'

export const apiCarriersIdGetPathIdSchema = z.string().describe('Carrier identifier')

export const apiCarriersIdGetStatus200SchemaLdJson = carrierJsonldCarrierReadSchema

export const apiCarriersIdGetStatus200SchemaJson = carrierCarrierReadSchema

export const apiCarriersIdGetStatus200Schema = z.union([apiCarriersIdGetStatus200SchemaLdJson, apiCarriersIdGetStatus200SchemaJson])

export const apiCarriersIdGetStatus404SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiCarriersIdGetStatus404SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiCarriersIdGetStatus404SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiCarriersIdGetStatus404Schema = z.union([apiCarriersIdGetStatus404SchemaLdJson, apiCarriersIdGetStatus404SchemaProblemJson, apiCarriersIdGetStatus404SchemaJson])

export const apiCarriersIdGetResponseSchema = apiCarriersIdGetStatus200Schema

export const apiCarriersIdGetErrorSchema = apiCarriersIdGetStatus404Schema
