/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'
import { hydraCollectionBaseSchemaSchema } from './hydraCollectionBaseSchemaSchema'
import { orderJsonldOrderReadSchema } from './order/jsonldOrder/readSchema'
import { orderOrderReadSchema } from './orderOrder/readSchema'

export const apiOrdersGetCollectionQueryPageSchema = z.int().optional().default(1).describe('The collection page number')

export const apiOrdersGetCollectionStatus200SchemaLdJson = hydraCollectionBaseSchemaSchema.extend({
  member: z.array(orderJsonldOrderReadSchema),
}).describe('Order.jsonld-order.read collection.')

export const apiOrdersGetCollectionStatus200SchemaJson = z.array(orderOrderReadSchema)

export const apiOrdersGetCollectionStatus200Schema = z.union([apiOrdersGetCollectionStatus200SchemaLdJson, apiOrdersGetCollectionStatus200SchemaJson])

export const apiOrdersGetCollectionStatus403SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiOrdersGetCollectionStatus403SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersGetCollectionStatus403SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersGetCollectionStatus403Schema = z.union([apiOrdersGetCollectionStatus403SchemaLdJson, apiOrdersGetCollectionStatus403SchemaProblemJson, apiOrdersGetCollectionStatus403SchemaJson])

export const apiOrdersGetCollectionResponseSchema = apiOrdersGetCollectionStatus200Schema

export const apiOrdersGetCollectionErrorSchema = apiOrdersGetCollectionStatus403Schema
