/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'
import { orderJsonldOrderReadSchema } from './order/jsonldOrder/readSchema'
import { orderOrderReadSchema } from './orderOrder/readSchema'

export const apiOrdersIdGetPathIdSchema = z.string().describe('Order identifier')

export const apiOrdersIdGetStatus200SchemaLdJson = orderJsonldOrderReadSchema

export const apiOrdersIdGetStatus200SchemaJson = orderOrderReadSchema

export const apiOrdersIdGetStatus200Schema = z.union([apiOrdersIdGetStatus200SchemaLdJson, apiOrdersIdGetStatus200SchemaJson])

export const apiOrdersIdGetStatus403SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiOrdersIdGetStatus403SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersIdGetStatus403SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersIdGetStatus403Schema = z.union([apiOrdersIdGetStatus403SchemaLdJson, apiOrdersIdGetStatus403SchemaProblemJson, apiOrdersIdGetStatus403SchemaJson])

export const apiOrdersIdGetStatus404SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiOrdersIdGetStatus404SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersIdGetStatus404SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersIdGetStatus404Schema = z.union([apiOrdersIdGetStatus404SchemaLdJson, apiOrdersIdGetStatus404SchemaProblemJson, apiOrdersIdGetStatus404SchemaJson])

export const apiOrdersIdGetResponseSchema = apiOrdersIdGetStatus200Schema

export const apiOrdersIdGetErrorSchema = z.union([apiOrdersIdGetStatus403Schema, apiOrdersIdGetStatus404Schema])
