/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { constraintViolationJsonldSchema } from './constraintViolation/jsonldSchema'
import { constraintViolationSchema } from './constraintViolationSchema'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'
import { orderJsonldOrderReadSchema } from './order/jsonldOrder/readSchema'
import { orderOrderReadSchema } from './orderOrder/readSchema'
import { orderOrderWriteSchema } from './orderOrder/writeSchema'

export const apiOrdersPostStatus201SchemaLdJson = orderJsonldOrderReadSchema

export const apiOrdersPostStatus201SchemaJson = orderOrderReadSchema

export const apiOrdersPostStatus201Schema = z.union([apiOrdersPostStatus201SchemaLdJson, apiOrdersPostStatus201SchemaJson])

export const apiOrdersPostStatus400SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiOrdersPostStatus400SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersPostStatus400SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersPostStatus400Schema = z.union([apiOrdersPostStatus400SchemaLdJson, apiOrdersPostStatus400SchemaProblemJson, apiOrdersPostStatus400SchemaJson])

export const apiOrdersPostStatus403SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiOrdersPostStatus403SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersPostStatus403SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersPostStatus403Schema = z.union([apiOrdersPostStatus403SchemaLdJson, apiOrdersPostStatus403SchemaProblemJson, apiOrdersPostStatus403SchemaJson])

export const apiOrdersPostStatus422SchemaLdJson = constraintViolationJsonldSchema.describe('Unprocessable entity')

export const apiOrdersPostStatus422SchemaProblemJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiOrdersPostStatus422SchemaJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiOrdersPostStatus422Schema = z.union([apiOrdersPostStatus422SchemaLdJson, apiOrdersPostStatus422SchemaProblemJson, apiOrdersPostStatus422SchemaJson])

export const apiOrdersPostResponseSchema = apiOrdersPostStatus201Schema

export const apiOrdersPostErrorSchema = z.union([apiOrdersPostStatus400Schema, apiOrdersPostStatus403Schema, apiOrdersPostStatus422Schema])

export const apiOrdersPostBodySchemaLdJson = orderOrderWriteSchema.describe('The new Order resource')

export const apiOrdersPostBodySchemaJson = orderOrderWriteSchema.describe('The new Order resource')

export const apiOrdersPostBodySchema = z.union([apiOrdersPostBodySchemaLdJson, apiOrdersPostBodySchemaJson])
