/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { constraintViolationJsonldSchema } from './constraintViolation/jsonldSchema'
import { constraintViolationSchema } from './constraintViolationSchema'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'

export const apiOrdersIddispatchPostPathIdSchema = z.string().describe('Order identifier')

export const apiOrdersIddispatchPostStatus202Schema = z.unknown()

export const apiOrdersIddispatchPostStatus400SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiOrdersIddispatchPostStatus400SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersIddispatchPostStatus400SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersIddispatchPostStatus400Schema = z.union([apiOrdersIddispatchPostStatus400SchemaLdJson, apiOrdersIddispatchPostStatus400SchemaProblemJson, apiOrdersIddispatchPostStatus400SchemaJson])

export const apiOrdersIddispatchPostStatus403SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiOrdersIddispatchPostStatus403SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersIddispatchPostStatus403SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiOrdersIddispatchPostStatus403Schema = z.union([apiOrdersIddispatchPostStatus403SchemaLdJson, apiOrdersIddispatchPostStatus403SchemaProblemJson, apiOrdersIddispatchPostStatus403SchemaJson])

export const apiOrdersIddispatchPostStatus422SchemaLdJson = constraintViolationJsonldSchema.describe('Unprocessable entity')

export const apiOrdersIddispatchPostStatus422SchemaProblemJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiOrdersIddispatchPostStatus422SchemaJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiOrdersIddispatchPostStatus422Schema = z.union([apiOrdersIddispatchPostStatus422SchemaLdJson, apiOrdersIddispatchPostStatus422SchemaProblemJson, apiOrdersIddispatchPostStatus422SchemaJson])

export const apiOrdersIddispatchPostResponseSchema = apiOrdersIddispatchPostStatus202Schema

export const apiOrdersIddispatchPostErrorSchema = z.union([apiOrdersIddispatchPostStatus400Schema, apiOrdersIddispatchPostStatus403Schema, apiOrdersIddispatchPostStatus422Schema])
