/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { constraintViolationJsonldSchema } from './constraintViolation/jsonldSchema'
import { constraintViolationSchema } from './constraintViolationSchema'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'
import { shippingRateShippingRateOutputJsonldSchema } from './shippingRate/shippingRateOutput/jsonldSchema'
import { shippingRateShippingRateOutputSchema } from './shippingRate/shippingRateOutputSchema'
import { shippingRateSchema } from './shippingRateSchema'

export const apiShippingcalculateRatesPostStatus201SchemaLdJson = shippingRateShippingRateOutputJsonldSchema

export const apiShippingcalculateRatesPostStatus201SchemaJson = shippingRateShippingRateOutputSchema

export const apiShippingcalculateRatesPostStatus201Schema = z.union([apiShippingcalculateRatesPostStatus201SchemaLdJson, apiShippingcalculateRatesPostStatus201SchemaJson])

export const apiShippingcalculateRatesPostStatus400SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiShippingcalculateRatesPostStatus400SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiShippingcalculateRatesPostStatus400SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiShippingcalculateRatesPostStatus400Schema = z.union([apiShippingcalculateRatesPostStatus400SchemaLdJson, apiShippingcalculateRatesPostStatus400SchemaProblemJson, apiShippingcalculateRatesPostStatus400SchemaJson])

export const apiShippingcalculateRatesPostStatus403SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiShippingcalculateRatesPostStatus403SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiShippingcalculateRatesPostStatus403SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiShippingcalculateRatesPostStatus403Schema = z.union([apiShippingcalculateRatesPostStatus403SchemaLdJson, apiShippingcalculateRatesPostStatus403SchemaProblemJson, apiShippingcalculateRatesPostStatus403SchemaJson])

export const apiShippingcalculateRatesPostStatus422SchemaLdJson = constraintViolationJsonldSchema.describe('Unprocessable entity')

export const apiShippingcalculateRatesPostStatus422SchemaProblemJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiShippingcalculateRatesPostStatus422SchemaJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiShippingcalculateRatesPostStatus422Schema = z.union([apiShippingcalculateRatesPostStatus422SchemaLdJson, apiShippingcalculateRatesPostStatus422SchemaProblemJson, apiShippingcalculateRatesPostStatus422SchemaJson])

export const apiShippingcalculateRatesPostResponseSchema = apiShippingcalculateRatesPostStatus201Schema

export const apiShippingcalculateRatesPostErrorSchema = z.union([apiShippingcalculateRatesPostStatus400Schema, apiShippingcalculateRatesPostStatus403Schema, apiShippingcalculateRatesPostStatus422Schema])

export const apiShippingcalculateRatesPostBodySchemaLdJson = shippingRateSchema.describe('The new ShippingRate resource')

export const apiShippingcalculateRatesPostBodySchemaJson = shippingRateSchema.describe('The new ShippingRate resource')

export const apiShippingcalculateRatesPostBodySchema = z.union([apiShippingcalculateRatesPostBodySchemaLdJson, apiShippingcalculateRatesPostBodySchemaJson])
