/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { constraintViolationJsonldSchema } from './constraintViolation/jsonldSchema'
import { constraintViolationSchema } from './constraintViolationSchema'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'
import { userJsonldUserReadSchema } from './user/jsonldUser/readSchema'
import { userUserInputUserWriteSchema } from './user/userInputUser/writeSchema'
import { userUserReadSchema } from './userUser/readSchema'

export const apiUsersPostStatus201SchemaLdJson = userJsonldUserReadSchema

export const apiUsersPostStatus201SchemaJson = userUserReadSchema

export const apiUsersPostStatus201Schema = z.union([apiUsersPostStatus201SchemaLdJson, apiUsersPostStatus201SchemaJson])

export const apiUsersPostStatus400SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiUsersPostStatus400SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiUsersPostStatus400SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiUsersPostStatus400Schema = z.union([apiUsersPostStatus400SchemaLdJson, apiUsersPostStatus400SchemaProblemJson, apiUsersPostStatus400SchemaJson])

export const apiUsersPostStatus403SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiUsersPostStatus403SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiUsersPostStatus403SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiUsersPostStatus403Schema = z.union([apiUsersPostStatus403SchemaLdJson, apiUsersPostStatus403SchemaProblemJson, apiUsersPostStatus403SchemaJson])

export const apiUsersPostStatus422SchemaLdJson = constraintViolationJsonldSchema.describe('Unprocessable entity')

export const apiUsersPostStatus422SchemaProblemJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiUsersPostStatus422SchemaJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiUsersPostStatus422Schema = z.union([apiUsersPostStatus422SchemaLdJson, apiUsersPostStatus422SchemaProblemJson, apiUsersPostStatus422SchemaJson])

export const apiUsersPostResponseSchema = apiUsersPostStatus201Schema

export const apiUsersPostErrorSchema = z.union([apiUsersPostStatus400Schema, apiUsersPostStatus403Schema, apiUsersPostStatus422Schema])

export const apiUsersPostBodySchemaLdJson = userUserInputUserWriteSchema.describe('The new User resource')

export const apiUsersPostBodySchemaJson = userUserInputUserWriteSchema.describe('The new User resource')

export const apiUsersPostBodySchema = z.union([apiUsersPostBodySchemaLdJson, apiUsersPostBodySchemaJson])
