/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'
import { userJsonldUserReadSchema } from './user/jsonldUser/readSchema'
import { userUserReadSchema } from './userUser/readSchema'

export const apiUsersIdGetPathIdSchema = z.string().describe('User identifier')

export const apiUsersIdGetStatus200SchemaLdJson = userJsonldUserReadSchema

export const apiUsersIdGetStatus200SchemaJson = userUserReadSchema

export const apiUsersIdGetStatus200Schema = z.union([apiUsersIdGetStatus200SchemaLdJson, apiUsersIdGetStatus200SchemaJson])

export const apiUsersIdGetStatus403SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiUsersIdGetStatus403SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiUsersIdGetStatus403SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiUsersIdGetStatus403Schema = z.union([apiUsersIdGetStatus403SchemaLdJson, apiUsersIdGetStatus403SchemaProblemJson, apiUsersIdGetStatus403SchemaJson])

export const apiUsersIdGetStatus404SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiUsersIdGetStatus404SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiUsersIdGetStatus404SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiUsersIdGetStatus404Schema = z.union([apiUsersIdGetStatus404SchemaLdJson, apiUsersIdGetStatus404SchemaProblemJson, apiUsersIdGetStatus404SchemaJson])

export const apiUsersIdGetResponseSchema = apiUsersIdGetStatus200Schema

export const apiUsersIdGetErrorSchema = z.union([apiUsersIdGetStatus403Schema, apiUsersIdGetStatus404Schema])
