/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'
import { userJsonldUserReadSchema } from './user/jsonldUser/readSchema'
import { userUserReadSchema } from './userUser/readSchema'

export const apiUsersmeGetStatus200SchemaLdJson = userJsonldUserReadSchema

export const apiUsersmeGetStatus200SchemaJson = userUserReadSchema

export const apiUsersmeGetStatus200Schema = z.union([apiUsersmeGetStatus200SchemaLdJson, apiUsersmeGetStatus200SchemaJson])

export const apiUsersmeGetStatus403SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiUsersmeGetStatus403SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiUsersmeGetStatus403SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiUsersmeGetStatus403Schema = z.union([apiUsersmeGetStatus403SchemaLdJson, apiUsersmeGetStatus403SchemaProblemJson, apiUsersmeGetStatus403SchemaJson])

export const apiUsersmeGetStatus404SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiUsersmeGetStatus404SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiUsersmeGetStatus404SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiUsersmeGetStatus404Schema = z.union([apiUsersmeGetStatus404SchemaLdJson, apiUsersmeGetStatus404SchemaProblemJson, apiUsersmeGetStatus404SchemaJson])

export const apiUsersmeGetResponseSchema = apiUsersmeGetStatus200Schema

export const apiUsersmeGetErrorSchema = z.union([apiUsersmeGetStatus403Schema, apiUsersmeGetStatus404Schema])
