/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'
import { hydraCollectionBaseSchemaSchema } from './hydraCollectionBaseSchemaSchema'
import { userJsonldUserReadSchema } from './user/jsonldUser/readSchema'
import { userUserReadSchema } from './userUser/readSchema'

export const apiUsersGetCollectionQueryPageSchema = z.int().optional().default(1).describe('The collection page number')

export const apiUsersGetCollectionStatus200SchemaLdJson = hydraCollectionBaseSchemaSchema.extend({
  member: z.array(userJsonldUserReadSchema),
}).describe('User.jsonld-user.read collection.')

export const apiUsersGetCollectionStatus200SchemaJson = z.array(userUserReadSchema)

export const apiUsersGetCollectionStatus200Schema = z.union([apiUsersGetCollectionStatus200SchemaLdJson, apiUsersGetCollectionStatus200SchemaJson])

export const apiUsersGetCollectionStatus403SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiUsersGetCollectionStatus403SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiUsersGetCollectionStatus403SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiUsersGetCollectionStatus403Schema = z.union([apiUsersGetCollectionStatus403SchemaLdJson, apiUsersGetCollectionStatus403SchemaProblemJson, apiUsersGetCollectionStatus403SchemaJson])

export const apiUsersGetCollectionResponseSchema = apiUsersGetCollectionStatus200Schema

export const apiUsersGetCollectionErrorSchema = apiUsersGetCollectionStatus403Schema
