/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { constraintViolationJsonldSchema } from './constraintViolation/jsonldSchema'
import { constraintViolationSchema } from './constraintViolationSchema'
import { errorJsonldSchema } from './error/jsonldSchema'
import { errorSchema } from './errorSchema'
import { userJsonldUserReadSchema } from './user/jsonldUser/readSchema'
import { userUserInputUserWriteJsonMergePatchSchema } from './user/userInputUser/write/jsonMergePatchSchema'
import { userUserReadSchema } from './userUser/readSchema'

export const apiUsersIdPatchPathIdSchema = z.string().describe('User identifier')

export const apiUsersIdPatchStatus200SchemaLdJson = userJsonldUserReadSchema

export const apiUsersIdPatchStatus200SchemaJson = userUserReadSchema

export const apiUsersIdPatchStatus200Schema = z.union([apiUsersIdPatchStatus200SchemaLdJson, apiUsersIdPatchStatus200SchemaJson])

export const apiUsersIdPatchStatus400SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiUsersIdPatchStatus400SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiUsersIdPatchStatus400SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiUsersIdPatchStatus400Schema = z.union([apiUsersIdPatchStatus400SchemaLdJson, apiUsersIdPatchStatus400SchemaProblemJson, apiUsersIdPatchStatus400SchemaJson])

export const apiUsersIdPatchStatus403SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiUsersIdPatchStatus403SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiUsersIdPatchStatus403SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiUsersIdPatchStatus403Schema = z.union([apiUsersIdPatchStatus403SchemaLdJson, apiUsersIdPatchStatus403SchemaProblemJson, apiUsersIdPatchStatus403SchemaJson])

export const apiUsersIdPatchStatus404SchemaLdJson = errorJsonldSchema.describe('A representation of common errors.')

export const apiUsersIdPatchStatus404SchemaProblemJson = errorSchema.describe('A representation of common errors.')

export const apiUsersIdPatchStatus404SchemaJson = errorSchema.describe('A representation of common errors.')

export const apiUsersIdPatchStatus404Schema = z.union([apiUsersIdPatchStatus404SchemaLdJson, apiUsersIdPatchStatus404SchemaProblemJson, apiUsersIdPatchStatus404SchemaJson])

export const apiUsersIdPatchStatus422SchemaLdJson = constraintViolationJsonldSchema.describe('Unprocessable entity')

export const apiUsersIdPatchStatus422SchemaProblemJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiUsersIdPatchStatus422SchemaJson = constraintViolationSchema.describe('Unprocessable entity')

export const apiUsersIdPatchStatus422Schema = z.union([apiUsersIdPatchStatus422SchemaLdJson, apiUsersIdPatchStatus422SchemaProblemJson, apiUsersIdPatchStatus422SchemaJson])

export const apiUsersIdPatchResponseSchema = apiUsersIdPatchStatus200Schema

export const apiUsersIdPatchErrorSchema = z.union([apiUsersIdPatchStatus400Schema, apiUsersIdPatchStatus403Schema, apiUsersIdPatchStatus404Schema, apiUsersIdPatchStatus422Schema])

export const apiUsersIdPatchBodySchema = userUserInputUserWriteJsonMergePatchSchema.describe('The updated User resource')
