/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const constraintViolationSchema = z.object({
  status: z.int().optional().default(422),
  violations: z.array(z.object({
    propertyPath: z.string().describe('The property path of the violation'),
    message: z.string().describe('The message associated with the violation'),
    code: z.string().optional().describe('The code of the violation'),
    hint: z.string().optional().describe('An extra hint to understand the violation'),
    payload: z.object({}).catchall(z.unknown()).optional().describe('The serialized payload of the violation'),
  })).optional(),
  detail: z.string().optional(),
  type: z.string().optional(),
  title: z.string().nullish(),
  instance: z.string().nullish(),
}).describe('Unprocessable entity')
