/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const errorSchema = z.object({
  title: z.string().nullish().describe('A short, human-readable summary of the problem.'),
  detail: z.string().nullish().describe('A human-readable explanation specific to this occurrence of the problem.'),
  status: z.int().nullish().default(400).meta({ examples: [404] }),
  instance: z.string().nullish().describe('A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.'),
  type: z.string().optional().describe('A URI reference that identifies the problem type'),
}).describe('A representation of common errors.')
