/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const hydraCollectionBaseSchemaNoPaginationSchema = z.object({
  totalItems: z.int().min(0).optional(),
  search: z.object({
    '@type': z.string().optional(),
    template: z.string().optional(),
    variableRepresentation: z.string().optional(),
    mapping: z.array(z.object({
      '@type': z.string().optional(),
      variable: z.string().optional(),
      property: z.string().nullish(),
      required: z.boolean().optional(),
    })).optional(),
  }).optional(),
})
