/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const hydraItemBaseSchemaSchema = z.object({
  '@context': z.union([
    z.string(),
    z.object({
      '@vocab': z.string(),
      hydra: z.enum(['http://www.w3.org/ns/hydra/core#']),
    }).catchall(z.unknown()),
  ]).optional(),
  '@id': z.string(),
  '@type': z.string(),
})
