/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { hydraCollectionBaseSchemaNoPaginationSchema } from './hydraCollectionBaseSchemaNoPaginationSchema'

export const hydraCollectionBaseSchemaSchema = hydraCollectionBaseSchemaNoPaginationSchema.extend({
  view: z.object({
    '@id': z.string().optional(),
    '@type': z.string().optional(),
    first: z.string().nullish(),
    last: z.string().nullish(),
    previous: z.string().nullish(),
    next: z.string().nullish(),
  }).optional().meta({ examples: [{}] }),
})
