/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const loginCheckPostStatus200Schema = z.object({
  token: z.string(),
})

export const loginCheckPostResponseSchema = loginCheckPostStatus200Schema

export const loginCheckPostBodySchema = z.object({
  username: z.string(),
  password: z.string(),
}).describe('The login data')
