/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const shippingRateSchema = z.object({
  dimensions: z.object({
    length: z.number().min(0).gt(0),
    width: z.number().min(0).gt(0),
    height: z.number().min(0).gt(0),
  }).strict(),
  weight: z.number().min(0).gt(0).default(0),
  destinationCountry: z.string().default(''),
})
