/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const orderOrderWriteSchema = z.object({
  client: z.string().optional().meta({ examples: ['https://example.com/'] }),
  carrier: z.string().optional().meta({ examples: ['https://example.com/'] }),
  items: z.array(z.string()).optional(),
  shippingAddress: z.array(z.string()).optional(),
  totalAmount: z.number().optional().default(0),
})
