/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const carrierCarrierWriteJsonMergePatchSchema = z.object({
  name: z.string().optional(),
  code: z.string().optional(),
  isActive: z.boolean().optional().default(true),
})
