/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const userUserReadSchema = z.object({
  id: z.int().optional(),
  email: z.string().optional(),
  roles: z.array(z.string()).optional(),
})
