/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const userUserInputUserWriteSchema = z.object({
  email: z.string().nullish(),
  password: z.string().nullish(),
  roles: z.array(z.string()).optional(),
})
