/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { hydraItemBaseSchemaSchema } from '../../hydraItemBaseSchemaSchema'

export const carrierJsonldOrderReadSchema = hydraItemBaseSchemaSchema.extend({
  id: z.int().optional(),
  name: z.string().optional(),
  code: z.string().optional(),
})
