/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { hydraItemBaseSchemaSchema } from '../../hydraItemBaseSchemaSchema'

export const shippingRateShippingRateOutputJsonldSchema = hydraItemBaseSchemaSchema.extend({
  rate: z.number().optional(),
  'calculation-id': z.string().optional(),
})
